### ISSUE TITLE
Been unable to play last versions because of crashings

### ISSUE THREAD

**Issue by marxosis** [AnsdoShip/carbonized-pixel-dungeon#1] opened 2022-07-01 19:45 UTC
Hello there! The last version i was able to play without problems was 0.0.5p3-ALPHA
I don't know if i am the only one with this problem but I have tried uninstall/install the newer versions that were released but after i launch the app it just crashes and gives me this log:

Build version: 0.0.7p7-ALPHA 
Current date: 2022-07-01 12:37:34 
Device: Xiaomi Redmi Note 9S 
OS version: Android 11 (SDK 30) 
 
Stack trace:  
java.lang.ExceptionInInitializerError
	at com.ansdoship.carbonizedpixeldungeon.messages.Messages.lang(Messages.java:50)
	at com.ansdoship.carbonizedpixeldungeon.scenes.PixelScene.create(PixelScene.java:126)
	at com.ansdoship.carbonizedpixeldungeon.scenes.SplashScene.create(SplashScene.java:28)
	at com.ansdoship.pixeldungeonclasses.noosa.Game.switchScene(Game.java:262)
	at com.ansdoship.carbonizedpixeldungeon.CarbonizedPixelDungeon.switchScene(CarbonizedPixelDungeon.java:196)
	at com.ansdoship.pixeldungeonclasses.noosa.Game.step(Game.java:239)
	at com.ansdoship.pixeldungeonclasses.noosa.Game.render(Game.java:174)
	at com.badlogic.gdx.backends.android.AndroidGraphics.onDrawFrame(AndroidGraphics.java:474)
	at android.opengl.GLSurfaceView$GLThread.guardedRun(GLSurfaceView.java:1577)
	at android.opengl.GLSurfaceView$GLThread.run(GLSurfaceView.java:1272)
Caused by: java.util.MissingResourceException: Can't find bundle for base file handle messages/actors/bigrat, locale 
	at com.badlogic.gdx.utils.I18NBundle.createBundleImpl(I18NBundle.java:200)
	at com.badlogic.gdx.utils.I18NBundle.createBundle(I18NBundle.java:132)
	at com.ansdoship.carbonizedpixeldungeon.messages.Messages.setup(Messages.java:85)
	at com.ansdoship.carbonizedpixeldungeon.messages.Messages.<clinit>(Messages.java:73)
	... 10 more

**Comment by Tianscar** [comment] 2022-07-05 15:24
This issue caused by weird read of property files under non-Chinese environments. It will be fixed at next version.

**Closed by Tianscar** 2022-07-05 15:24 UTC
